---

- include: setup-debian.yml
  when: ansible_os_family == "Debian"

- include: setup-redhat.yml
  when: ansible_os_family == "RedHat"

- name: Deploy elasticsearch config file
  template:
      src: elasticsearch.j2
      dest: /etc/elasticsearch/elasticsearch.yml
  notify:
      - restart elasticsearch
